#!/bin/bash

#nagios exit code
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

help () {
        local command=`basename $0`
        echo "NAME
        ${command} -- check docker storage spaces
SYNOPSIS
        ${command} [OPTION]
DESCRIPTION
        -w warning=<percent>
        -c critical=<percent>
USAGE:
        $0 -w 30 -c 20" 1>&2
        exit ${STATE_WARNING}
}

check_num () {
        local num_str="$1"
        echo ${num_str}|grep -E '^[0-9]+$' >/dev/null 2>&1 || local stat='not a positive integers!'
        if [ "${stat}" = 'not a positive integers!' ];then
                echo "${num_str} ${stat}" 1>&2
                exit ${STATE_WARNING}
        else
                local num_int=`echo ${num_str}*1|bc`
                if [ ${num_int} -lt 0 ];then
                        echo "${num_int} must be greater than 0!" 1>&2
                        exit ${STATE_WARNING}
                fi
        fi
}

#input
while getopts w:c: opt
do
        case "$opt" in
        w) 
                warning=$OPTARG
                warning_num=`echo "${warning}"|sed  's/%//g'`
                check_num "${warning_num}"
        ;;
        c) 
                critical=$OPTARG
                critical_num=`echo "${critical}"|sed  's/%//g'`
                check_num "${critical_num}"
        ;;
        *) help;;
        esac
done
shift $[ $OPTIND - 1 ]

[ $# -gt 0 -o -z "${warning_num}" -o -z "${critical_num}" ] && help

if [ -n "${warning_num}" -a -n "${critical_num}" ];then
        if [ ${critical_num} -ge ${warning_num} ];then
                echo "-w ${critical} must lower than -c ${warning}!" 1>&2
                exit ${STATE_UNKNOWN}
        fi
fi


space=`docker info 2>/dev/null|grep "Data Space Available"|awk -F ':' '{print $2}'`
space_num=`echo $space|awk '{print $1}'`
space_unit=`echo $space |awk '{print $NF}'`

message () {
local stat="$1"
echo "${stat} - : docker storage space : $space"
}

if [ $space_unit == GB ]
then
#	[ ${space_num} -gt ${warning_num} ] && message "OK" && exit ${STATE_OK}
	[ `echo $space_num \< ${warning_num} |bc ` -eq 0  ] && message "OK" && exit ${STATE_OK}
#	[ ${space_num} -le ${critical_num} ] && message "Critical" && exit ${STATE_CRITICAL}
	[ `echo $space_num \> ${critical_num} |bc ` -eq 0  ] && message "Critical" && exit ${STATE_CRITICAL}
#	[ ${space_num} -le ${warning_num} ] && message "Warning" && exit ${STATE_WARNING}
	[ `echo $space_num \> ${warning_num} |bc ` -eq 0  ] && message "Warning" && exit ${STATE_WARNING}


else
	message "Critical" && exit ${STATE_CRITICAL}
fi
